'^/wp-admin$':
  to: "/wp/wp-admin/"
  regexp: true
'^/wp-admin/(.*)':
  to: "/wp/wp-admin/$1"
  regexp: true
'^/ges/?$':
  to: "/offcampus/global-entry-semesters/"
  regexp: true
  code: 301
'^/global-entry/?$':
  to: "/offcampus/global-entry-semesters/"
  regexp: true
  code: 301
'^/ges/(.*)':
  to: "/offcampus/global-entry-semesters/$1"
  regexp: true
  code: 301
'^/global-entry/(.*)':
  to: "/offcampus/global-entry-semesters/$1"
  regexp: true
  code: 301
'^/health-services/?$':
  to: "/your-health/health-services/"
  regexp: true
  code: 301
'^/what-to-do/diversity-equity-inclusion/?$':
  to: "/what-to-do/multicultural-programs/"
  regexp: true
  code: 301
'^/offcampus/?$':
  to: "https://davisconnects.colby.edu/global-education-opportunities-geo/"
  regexp: true
  code: 301
'^/offcampus/watson-fellowship-overview/?$':
  to: "https://davisconnects.colby.edu/fellowships-advising/watson-fellowship-overview/"
  regexp: true
  code: 301
'^/offcampus/watson-fellowship-application-procedures/?$':
  to: "https://davisconnects.colby.edu/fellowships-advising/watson-fellowship-overview/watson-fellowship-application/"
  regexp: true
  code: 301